name: Update GitHub Pages

on:
  push:
    branches:
      - master  # Replace with the branch name you want to trigger the workflow on


jobs:
  update_pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10  # Replace with the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Markdown==3.4.3 rdflib==6.3.2  # Add any other dependencies if needed

      - name: Render documentation from ttl
        run: python docs/scripts/ttl_to_html.py

      - name: Render documentation from md
        run: python docs/scripts/md_to_html.py
